#! /usr/bin/env bash

# shellcheck disable=SC2154

dnf_(){
# remove packages
  if [[ -n "$removals" ]]; then
    dnf remove "${removals[@]}"
  fi

# install packages
  local core_packages=(
    'dnf-automatic'
    'htop'
    'wget'
    'bash-completion'
  )

  dnf install --assumeyes "${core_packages[@]}"

  if [[ -n "$default_packages" ]]; then
    dnf install --assumeyes "${default_packages[@]}"
  fi

  if [[ -n "$packages" ]]; then
    dnf install --assumeyes "${packages[@]}"
  fi

# auto update packages
  sed --in-place "s@^upgrade_type = .*@upgrade_type = ${update_type:=security}@" /etc/dnf/automatic.conf
  sed --in-place "s@^apply_updates = .*@apply_updates = yes@" /etc/dnf/automatic.conf

  systemctl daemon-reload
  systemctl enable --now dnf-automatic.timer
}

dnf_