#! /usr/bin/env bash

# shellcheck disable=SC2154

dnf_(){
# remove packages
  if [[ -n "$removals" ]]; then
    dnf remove "${removals[@]}"
  fi

# install packages
  local packages=(
    "dnf-automatic"
    "htop"
  )

  dnf install --assumeyes "${packages[@]}"

# auto update packages
  sed --in-place "s@^apply_updates = .*@apply_updates = yes@" /etc/dnf/automatic.conf

  systemctl daemon-reload
  systemctl enable --now dnf-automatic.timer
}

dnf_