#! /usr/bin/env bash

# shellcheck disable=SC2154

docker_() {
# intall packages
  local packages=(
    'curl'
  )

  dnf install --assumeyes "${packages[@]}"

# add user
  useradd --create-home "$docker_user"

# install docker
  bash <(curl -fsSL https://get.docker.com)

# enable
  systemctl enable --now docker.service

}

docker_