#! /usr/bin/env bash

# shellcheck disable=SC2154

flatpak_(){
# install flakpaks
  flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  flatpak install --noninteractive --assumeyes --or-update "${default_flatpaks[@]}"

  if [[ -n "$flatpaks" ]]; then
    flatpak install --noninteractive --assumeyes --or-update "${flatpaks[@]}"
  fi

# auto update flatpaks
  local packages=(
    "dbus-x11"
  )
  dnf install --assumeyes "${packages[@]}"

  tee /etc/systemd/system/flatpak-automatic.service > /dev/null <<EOF
[Unit]
Description=Flatpak - run flatpak update --assumeyes
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
ExecStart=dbus-launch flatpak update --noninteractive --assumeyes
Restart=on-failure
RestartSec=60s
EOF

  tee /etc/systemd/system/flatpak-automatic.timer > /dev/null <<EOF
[Unit]
Description=Flatpak - trigger for flatpak-automatic.service

[Timer]
OnBootSec=1h
OnUnitInactiveSec=1d
OnCalendar=daily
Persistent=true

[Install]
WantedBy=timers.target
EOF

# enable
  systemctl daemon-reload
  systemctl enable --now flatpak-automatic.timer

# flatpak overrides
# firefox
  if [[ "${default_flatpaks[*]}" =~ 'firefox' ]]; then
    flatpak override --socket=wayland --env=MOZ_ENABLE_WAYLAND=1 org.mozilla.firefox
  fi
}

flatpak_