#! /usr/bin/env bash

# shellcheck disable=SC2154

ssh_() {
# set vars
  local : "${ssh_port:=22}"

# install
  local packages=(
    'openssh-server'
    'firewalld'
    )

  dnf install --assumeyes "${packages[@]}"

# create config


  mkdir --mode=700 .ssh

  tee .ssh/authorized_keys > /dev/null <<EOF
$(printf "%s\n" "${ssh_auth_keys[@]}")
EOF
  chmod 600 .ssh/authorized_keys

  tee /etc/ssh/sshd_config.d/10-custom.conf > /dev/null <<EOF

Port ${ssh_port} 
PermitRootLogin yes
PubkeyAuthentication yes
PasswordAuthentication no
X11Forwarding no
EOF

  if [[ ! "$profile" = "lxc" ]]; then
    semanage port -a -t ssh_port_t -p tcp "$ssh_port"
  fi

  mkdir /etc/systemd/system/sshd.socket.d
  tee /etc/systemd/system/sshd.socket.d/override.conf > /dev/null <<EOF
[Socket]
ListenStream=
ListenStream=${ssh_port}
EOF

# enable
  systemctl daemon-reload
  systemctl disable --now sshd.service
  systemctl enable --now sshd.socket firewalld.service

  firewall-cmd --add-port="$ssh_port"/tcp --permanent --quiet
  if [[ ! "$ssh_port" = "22" ]]; then
    firewall-cmd --remove-service=ssh --permanent --quiet
  fi
  firewall-cmd --reload
}

ssh_