#! /usr/bin/env bash

syncthing_(){
# install packages
  local packages=(
    'syncthing'
    'firewalld'
  )

   dnf install --assumeyes "${packages[@]}"

# create config
  tee /etc/sysctl.d/40-max-user-watches.conf > /dev/null <<EOF
fs.inotify.max_user_watches=524288
EOF

# enable 
  systemctl enable --now syncthing@"$USER".service firewalld.service
  firewall-cmd --add-service=syncthing --permanent --quiet
  firewall-cmd --reload --quiet
}

syncthing_