#! /usr/bin/env bash

# shellcheck disable=SC2034
# shellcheck source=/dev/null

host_(){
# set vars
  profile='server'

  docker_user='docker'

# set profile
  source "$PWD"/../profiles/"$profile"

# load modules
  modules=(
    'docker'
  )

  for i in "${modules[@]}"; do
    source "$PWD"/../modules/"$i"
  done
}

host_

