#! /usr/bin/env bash

# shellcheck disable=SC2034
# shellcheck source=/dev/null

lxc_() {
# set vars


# load modules
  modules=(
    'hostnamectl'
    'bash_prompt'
    'dnf'
    'vim'
    )

  for i in "${modules[@]}"; do
    source "$PWD"/../modules/"$i"
  done
}

lxc_