#! /usr/bin/env bash

# shellcheck disable=SC2034
# shellcheck source=/dev/null

lxc_() {
# load modules
  lxc_modules=(
    'hostnamectl'
    'dnf'
    )

  for i in "${lxc_modules[@]}"; do
    source "$PWD"/../modules/"$i"
  done
}

lxc_